name: Build, lint and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run snyk-protect
      - run: npm run build

  test:
    needs: [build]

    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run lint
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: a8f8b7e6fd363b310aeb8887235ba85d390a0bfa2fcf374e154fbd1911c79570
        with:
          coverageCommand: npm run test:coverage
