# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run lint and tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: a8f8b7e6fd363b310aeb8887235ba85d390a0bfa2fcf374e154fbd1911c79570
        with:
          coverageCommand: npm run test:coverage
